import "./globals.css";
import Session from "@/components/Session";
import { GeistSans } from 'geist/font/sans'

export const metadata = {
  title: "Subty",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={GeistSans.className}>
        <Session>
          { children }
        </Session>
      </body>
    </html>
  );
}
